### ISSUE TITLE
自动初始化gitalk/gitment评论 | tenfy' blog

### ISSUE THREAD

**Issue by tenfyzhong** [tenfyzhong/tenfyzhong.github.io#48]
https://tenfy.cn/2018/11/15/auto-init-comment/

**Comment by njzjz** [comment]
```
$ ./bin/autoissue
new config config illegal
```
请问这是为什么？
log地址是https://travis-ci.com/njzjz/njzjz.github.io/builds/106467722#L1200

**Comment by tenfyzhong** [comment]
> @njzjz
> ```
> $ ./bin/autoissue
> new config config illegal
> ```
> 请问这是为什么？
> log地址是https://travis-ci.com/njzjz/njzjz.github.io/builds/106467722#L1200


参照step 3，需要添加以下的配置
```yml
owner: tenfyzhong
comment_repo: tenfyzhong.github.io # 对应于repo配置
labels: ["comment"]

sitemap:
  path: sitemap.xml
```
